<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cart;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $metaData = null)
    {
        parent::__construct($em, $metaData == null ?
            new Mapping\ClassMetadata(Cart::class) : $metaData
        );
    }

    public function create(Cart $cart)
    {
        try {
            $this->_em->persist($cart);
            $this->_em->flush($cart);
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    public function update(Cart $cart)
    {
        try {
            $this->_em->merge($cart);
            $this->_em->flush($cart);
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }

    }

    public function remove(Cart $cart)
    {
        try {
            $this->_em->remove($cart);
            $this->_em->flush($cart);
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
